### ISSUE TITLE
`get_codebook()` function

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/spanishoddata#3]
Credit for idea: @e-kotov

**Comment by e-kotov** [comment]
@Robinlovelace just thinking out loud how it should look like. I don't want to over engineer it (e.g. with [`codebook`](https://rubenarslan.github.io/codebook/) or [`codebookr`](https://brad-cannell.github.io/codebookr/) packages, which are not intended for documenting data in a package anyway and don't seem to integrate well with the package development tooling.

Possible options:

1. small samples of the data in data.frames documented like in a data package, like here https://github.com/jennybc/gapminder/blob/v0.3.0/R/gapminder.R
2. in a "Codebok" vignette
3. right inside the functions that actually fetch the data. The downside is that the data description is not very visible, as the description will be hidden away in the bottom of the function docs, below all the parameter descriptions.

Perhaps all of the above, should be easy to maintain since the data is stable.

what do you think?

**Comment by Robinlovelace** [comment]
Could just open up a web page as an MVP? Translation can happen later I guess.

**Comment by e-kotov** [comment]
Closed by #52
